#!/bin/bash
{ psql --user postgres <<-EOSQL
    CREATE USER "$DB_USER" WITH PASSWORD '$DB_PASSWORD';
    CREATE DATABASE "$DB_NAME" WITH OWNER="$DB_USER" TEMPLATE=template0 ENCODING='$DB_ENCODING';
    GRANT ALL PRIVILEGES ON DATABASE  "$DB_NAME" TO "$DB_USER";
EOSQL
}

psql $DB_NAME -c "CREATE EXTENSION IF NOT EXISTS postgis;"
psql $DB_NAME -c "CREATE EXTENSION IF NOT EXISTS postgis_topology;"
psql $DB_NAME -c "CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;"
psql $DB_NAME -c "CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;"
