#!/bin/bash
cat > /pg/data/postgresql.conf <<EOS
# Generated by fix-pgconf.sh
listen_addresses = '*'
#datestyle = 'iso, mdy'
log_statement = 'all'
# log_min_duration_statement (integer)
# TODO: ricorda di andarlo a cambiare sul server disabilitando lo all

#log_destination = 'stderr'
#standard_conforming_strings = off
# serve per evitare che gli oggetti LO abbiano un proprietario
#lo_compat_privileges=on
EOS
