  ppws:
    links:
      - "mydbpp:pp200.prv.lan"
      - "mydba400:pp20.prv.lan"
      - "mydba400:pp22.prv.lan"
    depends_on:
      - mypostfix
      - mydbpp
      - mydba400

  www:
    build: mywww
    container_name: www
    environment:
        VIRTUAL_HOST: www.portaportese.it, portaportese.it, wwwocean.portaportese.it, wwwlocal.portaportese.it 
        VIRTUAL_PORT: 80
    ports:
      - 80
    volumes:
      - ${LOGFOLDER}:/var/log/
      - ${PPFOLDER}/WEB-INF/ppappsrv04.httpd.conf:/etc/httpd/conf/httpd.conf
      - /mnt/volume-fra1-01/dump:/home/ppjr/default-ear/default-war/giornale/pdf
      - ${PPFOLDER}:/home/ppjr/default-ear/default-war
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "4"
    

  www:
    links:
      - "mydbpp:pp200.prv.lan"
      - "mydba400:pp20.prv.lan"
      - "mydba400:pp22.prv.lan"
    depends_on:
      - mydbpp
      - mydba400
      - ppws
      - mypostfix

      
  ppws:
    build: myjetty
    container_name: ppws
    environment:
        HTTPS_METHOD: noredirect
        VIRTUAL_HOST: data.portaportese.it, datalocal.portaportese.it, dataocean.portaportese.it
        VIRTUAL_PORT: 8080
    ports:
      - 8080
    depends_on:
      - myproxy
      - mypostfix
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "4"


// questo era production
version: '2'
services:
  www:
    extra_hosts:
      - "pp200.prv.lan:${IP_GESTIONALE}"
      - "pp20.prv.lan:${IP_DBA1}"
      - "pp22.prv.lan:${IP_DBA2}"
    depends_on:
      - ppws
      - mypostfix
  ppws:
    extra_hosts:
      - "pp200.prv.lan:${IP_GESTIONALE}"
      - "pp20.prv.lan:${IP_DBA1}"
      - "pp22.prv.lan:${IP_DBA2}"




  mydbpp:
    build: mydb
    container_name: mydbpp
    environment:
      DB_USER: pepper
      DB_PASSWORD: dbPasswordExampleLong 
      DB_NAME: portaportese
      DB_ENCODING: UTF-8    
      VIRTUAL_HOST: pp200.prv.lan
      VIRTUAL_PORT: 5432
    ports:
      - 5430:5432
    volumes:
      - ./Postgres/dbpp:/pg/data
      - ./Postgres/dumps:/pginput
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "4"

  mydba400:
    build: mydb
    container_name: mydba400
    environment:
        DB_USER: pepper
        DB_PASSWORD: dbPasswordExample
        DB_NAME: dba400L1
        DB_ENCODING: UTF-8    
        VIRTUAL_HOST: pp20.prv.lan, pp22.prv.lan
        VIRTUAL_PORT: 5432
    ports:
      - 5432:5432
    volumes:
      - ./Postgres/dba400:/pg/data
      - ./Postgres/dumps:/pginput
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "4"
