version: '2'
services:

  myproxy:
    build: myproxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ~/rmdtmsoft:/web/static
      - ~/cert:/etc/nginx/certs
      - ./nginx-vhost.d:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      default:
        aliases:
          - data.portaportese.it
  web:
    image: portaportese/ppstart:v1.2
    container_name: www
    command: /bin/bash /root/pplaunch
    environment:
        VIRTUAL_HOST: www.portaportese.it, ppappsrv03.inroma.roma.it, main.portaportese.it
        VIRTUAL_PORT: 8001
    ports:
      - 8001
    volumes:
      - ~/ppweb:/home/ppjr/default-ear/default-war
    extra_hosts:
      - "pp200.prv.lan:${IP_GESTIONALE}"
      - "pp20.prv.lan:${IP_DBA1}"
      - "pp22.prv.lan:${IP_DBA2}"
    depends_on:
        - ppws

  ppws:
    build: .
    container_name: datapp
    extra_hosts:
      - "pp200.prv.lan:${IP_GESTIONALE}"
      - "pp20.prv.lan:${IP_DBA1}"
      - "pp22.prv.lan:${IP_DBA2}"
    environment:
        VIRTUAL_HOST: data.portaportese.it, wslocal.portaportese.it
        VIRTUAL_PORT: 8080
    ports:
        - 8080
    depends_on:
        - myproxy
        - mypostfix

  mypostfix:
    image: catatnight/postfix
    container_name: mailer
    environment:
        maildomain: mail.portaportese.it
        smtp_user: ppmailer:ciccio123mail
    ports:
        - 25
