version: '2'
services:
  myproxy:
    build: myproxy
    container_name: ppproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${WEBFOLDER}:/web/static
      - ~/cert:/etc/nginx/certs
      - ~/ppdocker/myproxy/nginx-vhost.d:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      default:
        aliases:
          - portaportese.it
          - www.portaportese.it
          - data.portaportese.it
          - hookocean.portaportese.it
          - wwwocean.portaportese.it
          - dataocean.portaportese.it
          - wwwlocal.portaportese.it
          - datalocal.portaportese.it
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "4"

  www:
    build: mywww
    container_name: www
    environment:
        VIRTUAL_HOST: www.portaportese.it, portaportese.it, wwwocean.portaportese.it, wwwlocal.portaportese.it 
        VIRTUAL_PORT: 80
    ports:
      - 80
    volumes:
      - ${LOGFOLDER}:/var/log/
      - ${PPFOLDER}/WEB-INF/ppappsrv04.httpd.conf:/etc/httpd/conf/httpd.conf
      - /mnt/volume-fra1-01/dump:/home/ppjr/default-ear/default-war/giornale/pdf
      - ${PPFOLDER}:/home/ppjr/default-ear/default-war
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "4"

  webhook-service:
    build: myhook
    container_name: webhook-service
    environment:
        VIRTUAL_HOST: hookocean.portaportese.it 
    volumes:
      - ./myhook:/usr/src/app
      - /usr/src/app/node_modules
    #ports:
      # da togliere in produzione
      #- 3000:3000
      # da togliere in produzione
      #- 9229:9229
    command:
      node index.js 
      # da togliere in produzione
      # nodemon --inspect=0.0.0.0 index.js
    depends_on:
      - myproxy
      
  ppws:
    build: myjetty
    container_name: ppws
    environment:
        HTTPS_METHOD: noredirect
        VIRTUAL_HOST: data.portaportese.it, datalocal.portaportese.it, dataocean.portaportese.it
        VIRTUAL_PORT: 8080
    ports:
      - 8080
    depends_on:
      - myproxy
      - mypostfix
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "4"

  mypostfix:
    image: catatnight/postfix
    container_name: mailer
    environment:
      maildomain: mail.portaportese.it
      smtp_user: ppmailer:ciccio123mail
    ports:
      - 25
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "4"
