version: '2'
services:
  www:
    extra_hosts:
      - "pp200.prv.lan:${IP_GESTIONALE}"
      - "pp20.prv.lan:${IP_DBA1}"
      - "pp22.prv.lan:${IP_DBA2}"
    depends_on:
      - ppws
      - mypostfix
