version: '2'
services:

  myproxy:
    build: myproxy
    container_name: ppproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./rmdtmsoft:/web/static
      - ~/cert:/etc/nginx/certs
      - ~/ppdocker/nginx-vhost.d:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      
  mydb:
    image: postgres:9.4
    container_name: mydb
    ports:
      - 5432:5432
    volumes:
      - ./Postgres/var-9.4:/var/lib/postgresql/data

  web:
    image: portaportese/ppstart:v1.1
    container_name: www
    command: /bin/bash /root/pplaunch
    environment:
        VIRTUAL_HOST: www.portaportese.it, wwwlocal.portaportese.it, wwwocean.portaportese.mobi
        VIRTUAL_PORT: 80
    ports:
      - 80
    volumes:
      - ~/ppweb:/home/ppjr/default-ear/default-war
    links:
      - "mydb:pp200.prv.lan"
      - "mydb:pp20.prv.lan"
      - "mydb:pp22.prv.lan"
    depends_on:
        - mydb
        - ppws

  ppws:
    build: .
    container_name: datapp
    links:
      - "mydb:pp200.prv.lan"
      - "mydb:pp20.prv.lan"
      - "mydb:pp22.prv.lan"
    environment:
        HTTPS_METHOD: noredirect
        VIRTUAL_HOST: data.portaportese.it, datalocal.portaportese.it, dataocean.portaportese.mobi
        VIRTUAL_PORT: 8080
    ports:
        - 8080
    depends_on:
        - mydb
        - myproxy
        - mypostfix

  mypostfix:
    image: catatnight/postfix
    container_name: mailer
    environment:
        maildomain: mail.portaportese.it
        smtp_user: ppmailer:ciccio123mail
    ports:
        - 25
