version: '3'
services:
  mydb:
    build: mydb
    container_name: mydb
    environment:
      DB_USER: pepper
      DB_PASSWORD: dbPasswordExampleLong 
      DB_NAME: portaportese
      DB_ENCODING: UTF-8    
      VIRTUAL_HOST: ppnew.prv.lan
      VIRTUAL_PORT: 5432
    ports:
      - 5430:5432
    volumes:
      - ./Postgres/dbnew:/pg/data
      - ./Postgres/dumps:/pginput
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "4"
