version: "3"
services:

  mydb:
    build: mydb
    container_name: mydb
    environment:
      DB_USER: ${PGSQL_USER}
      DB_PASSWORD: ${PGSQL_PASSWORD} 
      DB_NAME: ${PGSQL_DATABASE}
      DB_ENCODING: UTF-8    
      #VIRTUAL_HOST: ppnew.prv.lan
      #VIRTUAL_PORT: 5432
    ports:
      - 5432:5432
    volumes:
      - /opt/dbnew:/pg/data
      - /opt/dumps:/pginput
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "4"

  mydbpp:
    build: mydbvecchio
    container_name: mydbpp
    environment:
      DB_USER: pepper
      DB_PASSWORD: ${PGSQL_PASSWORD2}
      DB_NAME: portaportese
      DB_ENCODING: UTF-8
    ports:
      - 5429:5432
    volumes:
      - /opt/dbpp:/pg/data
      - /opt/dumps:/pginput
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "4"

  mydba400:
    build: mydbvecchio
    container_name: mydba400
    environment:
        DB_USER: pepper
        DB_PASSWORD: ${PGSQL_PASSWORD3}
        DB_NAME: dba400L1
        DB_ENCODING: UTF-8
    ports:
      - 5430:5432
    volumes:
      - /opt/dba400:/pg/data
      - /opt/dumps:/pginput
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "4"
