#!/bin/bash
cat > /pg/data/postgresql.conf <<EOS
# Generated by fix-pgconf.sh
listen_addresses = '*'
datestyle = 'iso, mdy'
log_statement = 'all'
#log_destination = 'stderr'
standard_conforming_strings = off
# serve per evitare che gli oggetti LO abbiano un proprietario
lo_compat_privileges=on
EOS
